### ISSUE TITLE
sailfish dependency

### ISSUE THREAD

**Issue by dcjones** [COMBINE-lab/quark#3]
`quark.sh` depends on having `$sailfish` set, but the readme doesn't note having to set this, or even that sailfish is required. Worth mentioning somewhere!

**Comment by hiraksarkar** [comment]
Hi, 

Thanks for pointing this out. Quark is built on the top of sailfish. So it uses the framework, but it does not explicitly use sailfish. I forgot to change the binary name in `quark.sh`. It is fixed now with the latest commit 390c4f88102916575e6ec700171eb25159338b3d. Please let me know if that fixes the sailfish dependency.

**Comment by dcjones** [comment]
Yeah, that's better :+1:
